export const genders = [
  { value: "mr", valueName: "先生" },
  { value: "ms", valueName: "女士" },
  { value: "mx", valueName: "不明" },
]

export const cities = [
  { value: "KLU", cityName: "基隆市" },
  { value: "TPH", cityName: "新北市" },
  { value: "TPE", cityName: "臺北市" },
  { value: "TYC", cityName: "桃園市" },
  { value: "HSH", cityName: "新竹縣" },
  { value: "HSC", cityName: "新竹市" },
  { value: "MAC", cityName: "苗栗市" },
  { value: "MAL", cityName: "苗栗縣" },
  { value: "TXG", cityName: "臺中市" },
  { value: "CWH", cityName: "彰化縣" },
  { value: "CWS", cityName: "彰化市" },
  { value: "NTC", cityName: "南投市" },
  { value: "NTO", cityName: "南投縣" },
  { value: "YLH", cityName: "雲林縣" },
  { value: "CHY", cityName: "嘉義縣" },
  { value: "CYI", cityName: "嘉義市" },
  { value: "TNN", cityName: "臺南市" },
  { value: "KHH", cityName: "高雄市" },
  { value: "IUH", cityName: "屏東縣" },
  { value: "PTS", cityName: "屏東市" },
  { value: "ILN", cityName: "宜蘭縣" },
  { value: "ILC", cityName: "宜蘭市" },
  { value: "HWA", cityName: "花蓮縣" },
  { value: "HWC", cityName: "花蓮市" },
  { value: "TTC", cityName: "臺東市" },
  { value: "TTT", cityName: "臺東縣" },
  { value: "PEH", cityName: "澎湖縣" },
  { value: "KMN", cityName: "金門縣" },
  { value: "LNN", cityName: "連江縣" },
]
